### ISSUE TITLE
jsonを読み込めない問題

### ISSUE THREAD

**Issue by daiki510** [daiki510/mg_api#12]
## 概要
- JSONを読み込めないため下記エラーが発生している

```
SyntaxError: Unexpected token " in JSON at position 0
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (/Users/daikigoto/Github/mg_api/node_modules/body-parser/lib/types/json.js:158:10)
    at parse (/Users/daikigoto/Github/mg_api/node_modules/body-parser/lib/types/json.js:83:15)
    at /Users/daikigoto/Github/mg_api/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/Users/daikigoto/Github/mg_api/node_modules/raw-body/index.js:224:16)
    at done (/Users/daikigoto/Github/mg_api/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/Users/daikigoto/Github/mg_api/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by daiki510** [comment]
クローラーの側のリクエストの項目をjsonからbodyに変更
※ 別にjsonのままにしてプロセッサー側でjsonを使えばいいだけ
